// GENERATED FILE -- do not edit.
//
// Written by scripts/generate-catalogue.mjs, read straight out of the game files for
// Aghanim's Labyrinth III: Crisis of Infinite Dimensions (Steam workshop item 2483181385).
// Re-run `npm run catalogue:generate` after a game update; the diff is the changelog.

export const ITEM_CATEGORIES = ['advanced', 'consumable', 'encounter'] as const

export type ItemCategory = (typeof ITEM_CATEGORIES)[number]

/**
 * One stat line on an item.
 *
 * Unlike an artifact stat or an ability value, an item's number neither scales by a formula nor
 * grows by level -- the game writes it once -- so `value` is a single number, or the rare
 * string the KV leaves un-numeric.
 */
export type ItemValue = {
  key: string
  name: string
  value: number | string
  unit?: '%'
  /** Grows with the run's area-of-effect bonus. */
  scalesWithAoe?: boolean
}

export type Item = {
  slug: string
  /** The game's own id, so a row can be traced back to the KV it came from. */
  gameId: string
  name: string
  category: ItemCategory
  /**
   * Local art, or null. Only the mode's own items (potions, books, mushrooms) ship a texture in
   * the VPK; the reforged Dota items reuse Valve's stock art, resolved from the CDN via
   * `iconName` instead.
   */
  icon: string | null
  /** The game's texture name -- the local file's source, and the CDN key when there's no file. */
  iconName: string | null
  /** The game's own rarity word: consumable, rare, epic or artifact. */
  quality?: string
  /** Gold cost, when the item is bought rather than found. */
  cost?: number
  /** Shop stock cap, for the few items the shop rations. */
  stock?: number
  cooldown?: number
  manaCost?: number
  description?: string
  /** The smaller grey clarification the tooltip prints underneath. */
  note?: string
  flavor?: string
  values: ItemValue[]
}

export const ITEMS: Item[] = [
  {
    slug: "advanced-aether-lens",
    gameId: "item_advanced_aether_lens",
    name: "Advanced Aether Lens",
    category: "advanced",
    icon: null,
    iconName: "item_advanced_aether_lens",
    quality: "artifact",
    cost: 8000,
    description: "[[head]]Passive: Mana Focus[[/]]Restores [[value]]30[[/]]+[[value]]10%[[/]] lost mana per [[value]]5[[/]] seconds.",
    note: "Cast range bonuses do not stack with Aether Lens or upgraded items.",
    flavor: "Polished with the incantation of his final breath, the gift of a dying mage to his sickly son.",
    values: [
      {
        key: "bonus_mana",
        name: "Mana",
        value: 600,
      },
      {
        key: "bonus_mana_regen",
        name: "Mana Regeneration",
        value: 7,
      },
      {
        key: "cast_range_bonus",
        name: "Cast Range",
        value: 400,
      },
      {
        key: "cast_range_pct_bonus",
        name: "Cast Range",
        value: 15,
        unit: "%",
      },
    ],
  },
  {
    slug: "blade-mail2",
    gameId: "item_blade_mail2",
    name: "Advanced Blade Mail",
    category: "advanced",
    icon: null,
    iconName: "item_blade_mail_spectre_arcana_alt2",
    quality: "artifact",
    cost: 11000,
    cooldown: 25,
    manaCost: 50,
    description: "[[head]]Active: Damage Return[[/]]Reflects all incoming damage for [[value]]7[[/]] seconds at [[value]]170[[/]]% efficiency while providing [[value]]30[[/]]% damage reduction. [[head]]Passive: Damage Reflection[[/]]Reflects [[value]]40[[/]] + [[value]]25[[/]]% of Attack Damage on hit.of the attack damage dealt to you.",
    note: "Damage Return is calculated before any kind of reduction.",
    flavor: "A razor-sharp coat of mail, it is the choice of selfless martyrs in combat.",
    values: [
      {
        key: "bonus_damage",
        name: "Attack Damage",
        value: 40,
      },
      {
        key: "bonus_armor",
        name: "Armor",
        value: 20,
      },
      {
        key: "damage_reduction",
        name: "Damage Reduction",
        value: 15,
        unit: "%",
      },
    ],
  },
  {
    slug: "greater-crit2",
    gameId: "item_greater_crit2",
    name: "Advanced Daedalus",
    category: "advanced",
    icon: null,
    iconName: "item_greater_crit_drow_arcana",
    quality: "artifact",
    cost: 11000,
    description: "[[head]]Passive: Critical Strike[[/]]Grants each attack a [[value]]35%[[/]] chance to deal [[value]]280%[[/]] damage.",
    note: "Critical Strike does not work against buildings.",
    flavor: "A weapon of incredible power that is difficult for even the strongest of warriors to control.",
    values: [
      {
        key: "bonus_damage",
        name: "Attack Damage",
        value: 200,
      },
      {
        key: "crit_multiplier_final",
        name: "Final Strike Damage",
        value: 20,
        unit: "%",
      },
    ],
  },
  {
    slug: "dagon-6",
    gameId: "item_dagon_6",
    name: "Advanced Dagon",
    category: "advanced",
    icon: null,
    iconName: "item_dagon_6",
    cooldown: 15,
    manaCost: 300,
    description: "[[head]]Active: Energy Blast[[/]]Deals massive damage to the target and up to [[value]]8[[/]] opponents within [[value]]400[[/]] around it, damage increased by [[value]]50%[[/]](×) for targets above [[value]]75%[[/]] HP.[[color:#4ecbe7]]Damage: [[value]]1800[[/]]\nPrimary attribute damage: [[value]]2500%[[/]][[/]]\nMana Cost: [[value]]300[[/]]",
    flavor: "A secondary staff that grows more powerful with use, allowing the wielder's magic to gush from their fingertips.",
    values: [
      {
        key: "bonus_all_stats",
        name: "All Attributes",
        value: 40,
      },
      {
        key: "bonus_health",
        name: "Health",
        value: 600,
      },
      {
        key: "bonus_mana",
        name: "Mana",
        value: 800,
      },
      {
        key: "cast_range_bonus",
        name: "Cast Range",
        value: 200,
      },
    ],
  },
  {
    slug: "desolator2",
    gameId: "item_desolator2",
    name: "Advanced Desolator",
    category: "advanced",
    icon: null,
    iconName: "item_desolator2",
    description: "[[head]]Passive: Greater Corruption[[/]] Attacks reduce the target's armor by [[value]]30[[/]] for [[value]]12[[/]] seconds.",
    values: [
      {
        key: "damage",
        name: "Attack Damage",
        value: 150,
      },
    ],
  },
  {
    slug: "ethereal-blade2",
    gameId: "item_ethereal_blade2",
    name: "Advanced Ethereal Blade",
    category: "advanced",
    icon: null,
    iconName: "item_ethereal_blade2",
    description: "[[head]]Active: Ether Blast[[/]]Fires an energy wave, that applies to the target and up to [[value]]6[[/]] enemies within [[value]]300[[/]], disarming them and reducing their magic resistance by [[value]]-40[[/]] for [[value]]4[[/]] seconds. While affected, they take [[value]]70%[[/]] less physical damage. When targeting an enemy, deals [[color:#4ecbe7]][[value]]1500[[/]] + [[value]]600%[[/]] of all attributes[[/]] damage and applies a [[value]]80%[[/]] movement slow for [[value]]4[[/]] seconds.\nWhen targeting an ally, grants them [[value]]40%[[/]] bonus movement speed for [[value]]4[[/]] seconds.",
    flavor: "A flickering, eerie blade that can deal damage in both the physical and magical planes.",
    values: [
      {
        key: "bonus_agility",
        name: "All Attributes",
        value: 39,
      },
      {
        key: "bonus_spell_amp",
        name: "Spell AMP",
        value: 15,
        unit: "%",
      },
    ],
  },
  {
    slug: "gungir2",
    gameId: "item_gungir2",
    name: "Advanced Gleipnir",
    category: "advanced",
    icon: null,
    iconName: "item_gungir2",
    cooldown: 18,
    manaCost: 150,
    description: "[[head]]Active: Eternal Chains[[/]]Roots all enemies in a [[value]]400[[/]] radius for [[value]]2[[/]] seconds.",
    flavor: "Bindings forged by impossible means to leash an ancient evil.",
    values: [
      {
        key: "bonus_aoe",
        name: "Area of Effect",
        value: 120,
      },
      {
        key: "aoe_pct",
        name: "Area of Effect",
        value: 15,
        unit: "%",
      },
      {
        key: "bonus_hp",
        name: "Health",
        value: 800,
      },
      {
        key: "bonus_intellect",
        name: "Intelligence",
        value: 25,
      },
      {
        key: "bonus_mana",
        name: "Mana",
        value: 500,
      },
    ],
  },
  {
    slug: "mjollnir2",
    gameId: "item_mjollnir2",
    name: "Advanced Mjollnir",
    category: "advanced",
    icon: null,
    iconName: "item_mjollnir2",
    quality: "artifact",
    cost: 10000,
    cooldown: 35,
    manaCost: 50,
    description: "[[head]]Active: Static Shock[[/]]Places a Static Shield on the target unit for [[value]]15[[/]] seconds. The shield has a [[value]]20%[[/]] chance to release a lightning strike when attacked, hitting the attacker and up to [[value]]4[[/]] nearby enemy units, dealing [[color:#4ecbe7]]([[value]]600[[/]]+[[value]]400%[[/]] primary attributes)[[/]] magic damage. [[head]]Passive: Chain Lightning[[/]]Attacks have a [[value]]25%[[/]] chance to release a chain lightning that leaps between up to [[value]]12[[/]] targets within [[value]]650[[/]] range, dealing [[color:#4ecbe7]]([[value]]400[[/]]+[[value]]200%[[/]] primary attributes)[[/]] [[color:#a3a5f7ff]]Orb effect[[/]] magic damage per leap. Chain Lightning ignores evasion. Benefits from [[value]]160%[[/]] spell amp.",
    note: "Static Charge cannot trigger more than once per second.",
    flavor: "Thor's magical hammer, made for him by the dwarves Brokkr and Eitri.",
    values: [
      {
        key: "bonus_damage",
        name: "Attack Damage",
        value: 80,
      },
      {
        key: "bonus_attack_speed",
        name: "Attack Damage",
        value: 150,
      },
    ],
  },
  {
    slug: "radiance2",
    gameId: "item_radiance2",
    name: "Advanced Radiance",
    category: "advanced",
    icon: null,
    iconName: "item_radiance_spectre_arcana_alt2",
    quality: "artifact",
    description: "[[head]]Toggle: Burn[[/]] When active, scorches enemies for [[color:#4ecbe7]]([[value]]175%[[/]] primary attribute + [[value]]200[[/]])[[/]] magic damage per second. Radius: [[value]]800[[/]].",
    flavor: "A divine weapon that causes damage and a bright burning effect that lays waste to nearby enemies.",
    values: [
      {
        key: "bonus_damage",
        name: "Attack Damage",
        value: 80,
      },
      {
        key: "evasion",
        name: "Evasion",
        value: 30,
        unit: "%",
      },
      {
        key: "all_attribute",
        name: "All Attributes",
        value: 30,
      },
    ],
  },
  {
    slug: "attribute-stone",
    gameId: "item_attribute_stone",
    name: "Attribute Gem",
    category: "advanced",
    icon: null,
    iconName: "item_attribute_stone",
    cost: 4300,
    description: "[[head]]Passive: Tri-Color Radiance[[/]]When calculating damage, healing, or shield effects, the calculation results of your Strength, Agility, and Intelligence are increased by [[value]]25%[[/]].",
    note: "Does not work on special effects such as secondary attributes, transformation effects, etc",
    flavor: "A gem stripped from an ancient artifact, though its power has greatly diminished.",
    values: [
      {
        key: "bonus_attribute",
        name: "All Attributes",
        value: 20,
      },
    ],
  },
  {
    slug: "attribute-stone2",
    gameId: "item_attribute_stone2",
    name: "Attribute Gem +",
    category: "advanced",
    icon: null,
    iconName: "item_attribute_stone2",
    cost: 9000,
    description: "[[head]]Passive: Tri-Color Radiance[[/]]When calculating damage, healing, or shield effects, the calculation results of your Strength, Agility, and Intelligence are increased by [[value]]45%[[/]].",
    note: "Does not apply to special effects such as secondary attributes and transformation-type effects",
    flavor: "A gem stripped from an ancient artifact, partially restored after repairs and now regaining some of its power.",
    values: [
      {
        key: "bonus_attribute",
        name: "All Attributes",
        value: 35,
      },
    ],
  },
  {
    slug: "eternal-shroud-override",
    gameId: "item_eternal_shroud_override",
    name: "Eternal Shroud",
    category: "advanced",
    icon: null,
    iconName: "item_eternal_shroud_override",
    description: "[[head]]Passive: Shroud[[/]] Converts [[value]]25%[[/]] of ability damage taken before reductions into mana. [[head]]Passive: Eternal Endurance[[/]] For every ([[value]]200[[/]] + [[value]]5%[[/]]) max HP of ability damage the equipped hero receives, it gains a stack for [[value]]5[[/]] seconds, up to a maximum of [[value]]6[[/]] stacks. Each stack increases Eternal Shroud's magic armor by [[value]]5[[/]].",
    note: "Eternal Shroud does not respond to damage or HP loss without a source.",
    flavor: "A discarded robe, now making a comeback.",
    values: [
      {
        key: "bonus_spell_resist",
        name: "Magic Armor",
        value: 30,
      },
      {
        key: "bonus_strength",
        name: "Strength",
        value: 10,
      },
      {
        key: "bonus_health",
        name: "Health",
        value: 250,
      },
    ],
  },
  {
    slug: "bloodstone2",
    gameId: "item_bloodstone2",
    name: "Greater Bloodstone",
    category: "advanced",
    icon: null,
    iconName: "item_bloodstone2",
    cooldown: 30,
    description: "[[head]]Active: Blood Tribute[[/]]Spell lifesteal increased to [[value]]60%[[/]], and gain [[value]]15%[[/]] spell amp for [[value]]5[[/]] seconds. [[head]]Passive: Greater Spell Weakness Aura[[/]]Enemy units take [[value]]22%[[/]] bonus spell damage. Radius: [[value]]1200[[/]]",
    note: "Vulnerability effect does not stack with Bloodstone, Veil Of Discord.",
    flavor: "The crimson hue of the Bloodstone is unmistakable on the battlefield. Its bearer seems to possess an endless supply of vitality and energy.",
    values: [
      {
        key: "bonus_health",
        name: "Health",
        value: 800,
      },
      {
        key: "bonus_mana",
        name: "Mana",
        value: 600,
      },
      {
        key: "bonus_intellect",
        name: "Intelligence",
        value: 35,
      },
      {
        key: "spell_lifesteal_inc_pure",
        name: "Attack Lifesteal (Including Pure Lifesteal)",
        value: 20,
        unit: "%",
      },
    ],
  },
  {
    slug: "butterfly2",
    gameId: "item_butterfly2",
    name: "Greater Butterfly",
    category: "advanced",
    icon: null,
    iconName: "item_butterfly2",
    flavor: "Butterfly provides unparalleled rewards for seasoned warriors.",
    values: [
      {
        key: "bonus_agility",
        name: "Agility",
        value: 70,
      },
      {
        key: "bonus_evasion",
        name: "Evasion",
        value: 35,
        unit: "%",
      },
      {
        key: "bonus_attack_speed_pct",
        name: "Attack Damage",
        value: 12,
        unit: "%",
      },
      {
        key: "bonus_damage",
        name: "Attack Damage",
        value: 70,
      },
      {
        key: "attack_interval",
        name: "Attack Interval",
        value: 0.1,
      },
    ],
  },
  {
    slug: "helm-of-the-overlord2",
    gameId: "item_helm_of_the_overlord2",
    name: "Greater Helm of the Overlord",
    category: "advanced",
    icon: null,
    iconName: "item_helm_of_the_overlord2",
    cooldown: 30,
    manaCost: 150,
    description: "[[head]]Active: Forced Command[[/]] Deals [[value]]30%[[/]] of max HP as damage to your summons within [[value]]1200[[/]] range, then grants them [[value]]35%[[/]] armor and magic armor penetration for [[value]]12[[/]] seconds.\n[[head]]Passive: Overlord's Command[[/]] Summons gain +[[value]]35%[[/]] attack damage.",
    note: "Summon bonuses and passive effects do not stack",
    values: [
      {
        key: "bonus_stats",
        name: "All Attributes",
        value: 36,
      },
      {
        key: "bonus_armor",
        name: "Armor",
        value: 10,
      },
      {
        key: "bonus_regen",
        name: "Health Regeneration",
        value: 10,
      },
      {
        key: "bonus_summon_intensity",
        name: "Summon AMP",
        value: 26,
        unit: "%",
      },
    ],
  },
  {
    slug: "devastator2",
    gameId: "item_devastator2",
    name: "Greater Parasma",
    category: "advanced",
    icon: null,
    iconName: "item_devastator2",
    cooldown: 3,
    description: "[[head]]Passive: Witch Blade[[/]]Causes the next attack to gain True Strike and deal bonus [[color:#4ecbe7]]([[value]]400[[/]] + [[value]]650%[[/]]) of primary attributes[[/]] [[color:#a3a5f7ff]]Orb[[/]] magic damage, while slowing the enemy by [[value]]40%[[/]] movement speed for [[value]]2[[/]] seconds. Benefits from [[value]]160%[[/]] spell amp.\n[[head]]Passive: Mana Corrosion[[/]]Attacks reduce the enemy's magic armor by [[value]]30[[/]] for [[value]]2[[/]] seconds.",
    flavor: "Warning: There is no cure if you grab the other end.",
    values: [
      {
        key: "bonus_intellect",
        name: "Intelligence",
        value: 50,
      },
      {
        key: "bonus_attack_speed",
        name: "Attack Damage",
        value: 100,
      },
      {
        key: "bonus_armor",
        name: "Armor",
        value: 10,
      },
      {
        key: "bonus_mana_regen",
        name: "Mana Regeneration",
        value: 4,
      },
      {
        key: "projectile_speed",
        name: "Projectile Speed",
        value: 300,
      },
    ],
  },
  {
    slug: "sheepstick2",
    gameId: "item_sheepstick2",
    name: "Greater Scythe Of Vyse",
    category: "advanced",
    icon: null,
    iconName: "item_sheepstick2",
    cooldown: 20,
    manaCost: 350,
    description: "[[head]]Active: Oink![[/]]Applies Hex to the target and up to [[value]]6[[/]] enemies within [[value]]300[[/]] range, lasting [[value]]4[[/]] seconds. The target is muted, silenced, disarmed, and slowed, taking [[value]]25%[[/]] bonus damage.",
    flavor: "Thus, the Pig King took out its precious Pig Wand.",
    values: [
      {
        key: "bonus_atb",
        name: "All Attributes",
        value: 40,
      },
      {
        key: "bonus_mana_regen",
        name: "Mana Regeneration",
        value: 10,
      },
      {
        key: "bonus_debuff_duration",
        name: "Debuff Duration",
        value: 20,
        unit: "%",
      },
    ],
  },
  {
    slug: "helm-of-the-dominator",
    gameId: "item_helm_of_the_dominator",
    name: "Helm Of The Dominator",
    category: "advanced",
    icon: null,
    iconName: "item_helm_of_the_dominator",
    values: [
      {
        key: "bonus_summon_intensity",
        name: "Summon AMP",
        value: 14,
        unit: "%",
      },
    ],
  },
  {
    slug: "helm-of-the-overlord",
    gameId: "item_helm_of_the_overlord",
    name: "Helm Of The Overlord",
    category: "advanced",
    icon: null,
    iconName: "item_helm_of_the_overlord",
    description: "[[head]]Passive: Overlord's Command[[/]] Summons gain +[[value]]25%[[/]] Attack Damage.",
    note: "Summon bonuses and passive effects do not stack",
    values: [
      {
        key: "bonus_summon_intensity",
        name: "Summon AMP",
        value: 20,
        unit: "%",
      },
    ],
  },
  {
    slug: "holy-locket",
    gameId: "item_holy_locket",
    name: "Holy Locket",
    category: "advanced",
    icon: null,
    iconName: "item_holy_locket",
    cooldown: 20,
    description: "[[head]]Active: Divine Healing[[/]]Target an allied unit to instantly restore [[value]]350[[/]] Health and Mana. [[head]]Passive: Holy Blessing[[/]]Amplifies heals you provide by [[value]]15%[[/]].",
    flavor: "A prized relic long thought lost forever in a failed crusade.",
    values: [
      {
        key: "bonus_all_stats",
        name: "All Attributes",
        value: 9,
      },
    ],
  },
  {
    slug: "arcanist-potion",
    gameId: "item_arcanist_potion",
    name: "Arcanist Potion",
    category: "consumable",
    icon: "/items/arcanist-potion.png",
    iconName: "arcanist_potion",
    quality: "rare",
    stock: 1,
    description: "[[head]]Use: Arcane Empowerment[[/]]Reduces Ability cooldowns and Mana costs.",
    values: [
      {
        key: "duration",
        name: "Duration",
        value: 90,
      },
      {
        key: "cooldown_reduction_pct",
        name: "Cooldown Reduction",
        value: 30,
        unit: "%",
      },
      {
        key: "manacost_reduction_pct",
        name: "Mana Cost Reduction",
        value: 50,
        unit: "%",
      },
    ],
  },
  {
    slug: "book-of-agility",
    gameId: "item_book_of_agility",
    name: "Book of Agility",
    category: "consumable",
    icon: "/items/book-of-agility.png",
    iconName: "book_of_agility",
    quality: "rare",
    cost: 500,
    description: "On use: permanently gain [[value]]5[[/]] base Agility.",
    values: [],
  },
  {
    slug: "book-of-greater-agility2",
    gameId: "item_book_of_greater_agility2",
    name: "Book of Extreme Agility",
    category: "consumable",
    icon: "/items/book-of-greater-agility2.png",
    iconName: "book_of_agility3",
    quality: "artifact",
    cost: 1000,
    description: "On use: permanently gain [[value]]15[[/]] base Agility.",
    values: [],
  },
  {
    slug: "book-of-greater-strength",
    gameId: "item_book_of_greater_strength",
    name: "Book of Fortitude",
    category: "consumable",
    icon: "/items/book-of-greater-strength.png",
    iconName: "book_of_strength2",
    quality: "epic",
    cost: 1000,
    description: "On use: permanently gain [[value]]10[[/]] base Strength.",
    values: [],
  },
  {
    slug: "book-of-greater-strength2",
    gameId: "item_book_of_greater_strength2",
    name: "Book of Greater Strength",
    category: "consumable",
    icon: "/items/book-of-greater-strength2.png",
    iconName: "book_of_strength3",
    quality: "artifact",
    cost: 1000,
    description: "On use: permanently gain [[value]]15[[/]] base Strength.",
    values: [],
  },
  {
    slug: "book-of-greater-intelligence",
    gameId: "item_book_of_greater_intelligence",
    name: "Book of Insight",
    category: "consumable",
    icon: "/items/book-of-greater-intelligence.png",
    iconName: "book_of_intelligence2",
    quality: "epic",
    cost: 1000,
    description: "On use: permanently gain [[value]]10[[/]] base Intelligence.",
    values: [],
  },
  {
    slug: "book-of-intelligence",
    gameId: "item_book_of_intelligence",
    name: "Book of Intelligence",
    category: "consumable",
    icon: "/items/book-of-intelligence.png",
    iconName: "book_of_intelligence",
    quality: "rare",
    cost: 500,
    description: "On use: permanently gain [[value]]5[[/]] base Intelligence.",
    values: [],
  },
  {
    slug: "book-of-strength",
    gameId: "item_book_of_strength",
    name: "Book of Strength",
    category: "consumable",
    icon: "/items/book-of-strength.png",
    iconName: "book_of_strength",
    quality: "rare",
    cost: 500,
    description: "On use: permanently gain [[value]]5[[/]] base Strength.",
    values: [],
  },
  {
    slug: "book-of-greater-intelligence2",
    gameId: "item_book_of_greater_intelligence2",
    name: "Book of Supreme Intelligence",
    category: "consumable",
    icon: "/items/book-of-greater-intelligence2.png",
    iconName: "book_of_intelligence3",
    quality: "artifact",
    cost: 1000,
    description: "On use: permanently gain [[value]]15[[/]] base Intelligence.",
    values: [],
  },
  {
    slug: "book-of-greater-agility",
    gameId: "item_book_of_greater_agility",
    name: "Book of Swiftness",
    category: "consumable",
    icon: "/items/book-of-greater-agility.png",
    iconName: "book_of_agility2",
    quality: "epic",
    cost: 1000,
    description: "On use: permanently gain [[value]]10[[/]] base Agility.",
    values: [],
  },
  {
    slug: "dragon-potion",
    gameId: "item_dragon_potion",
    name: "Dragon Potion",
    category: "consumable",
    icon: "/items/dragon-potion.png",
    iconName: "dragon_potion",
    quality: "rare",
    stock: 1,
    description: "[[head]]Use: Dragon Form[[/]]Embrace the power of an Elder Dragon, increasing your Armor, Magic Armor, Movement Speed, and Attack Damage for a short duration.",
    note: "All bonuses expire at the end of the Round.",
    values: [
      {
        key: "duration",
        name: "Duration",
        value: 180,
      },
      {
        key: "bonus_movement_speed",
        name: "Bonus Move Speed",
        value: 40,
        unit: "%",
      },
      {
        key: "bonus_attack_damage",
        name: "Attack Damage Bonus",
        value: 30,
      },
      {
        key: "bonus_attack_damage_pct",
        name: "Attack Damage Bonus",
        value: 60,
        unit: "%",
      },
      {
        key: "magic_armor",
        name: "Magic Armor",
        value: 40,
      },
      {
        key: "armor",
        name: "Armor",
        value: 15,
      },
    ],
  },
  {
    slug: "eccentric-stew",
    gameId: "item_eccentric_stew",
    name: "Eccentric Stew",
    category: "consumable",
    icon: "/items/eccentric-stew.png",
    iconName: "eccentric_stew",
    quality: "artifact",
    description: "[[head]]Consume: Eat It[[/]]Grants [[value]]2[[/]] random different Common Shard upgrades, effective for this round only.",
    flavor: "A strange stew brewed from creatures of the Dark Reef—unappealing to look at, yet it lets you steal a trace of temporary power.",
    values: [],
  },
  {
    slug: "potion-of-growth",
    gameId: "item_potion_of_growth",
    name: "Elixir of Flourish",
    category: "consumable",
    icon: "/items/potion-of-growth.png",
    iconName: "potion_of_growth",
    quality: "artifact",
    description: "[[head]]Consume: Flourish[[/]]Permanently increases your Primary Attribute Growth by [[value]]2[[/]].",
    note: "Universal Heroes gain [[value]]0.8[[/]] growth to all Attributes.",
    flavor: "Unlimited potential...",
    values: [],
  },
  {
    slug: "potion-of-growth-shop",
    gameId: "item_potion_of_growth_shop",
    name: "Elixir of Flourish",
    category: "consumable",
    icon: "/items/potion-of-growth-shop.png",
    iconName: "potion_of_growth",
    quality: "artifact",
    description: "[[head]]Consume: Flourish[[/]]Permanently increases your Primary Attribute Growth by [[value]]1.5[[/]].",
    note: "Universal Heroes gain [[value]]0.6[[/]] growth to all Attributes.",
    flavor: "Unlimited potential...",
    values: [],
  },
  {
    slug: "hd-bottle-water",
    gameId: "item_hd_bottle_water",
    name: "Filled Bottle",
    category: "consumable",
    icon: null,
    iconName: "item_bottle_water",
    quality: "epic",
    description: "[[head]]Consume: Refill[[/]]Fully refills your Bottle charges.",
    flavor: "Ah, ready to fight again.",
    values: [],
  },
  {
    slug: "lotus",
    gameId: "item_lotus",
    name: "Healing Lotus",
    category: "consumable",
    icon: null,
    iconName: "item_great_famango",
    quality: "consumable",
    description: "Fully restores all allied Heroes’ HP and reduces a random Ability’s Cooldown by [[value]]3[[/]] seconds for each upon pickup.",
    values: [],
  },
  {
    slug: "health-potion",
    gameId: "item_health_potion",
    name: "HP Potion",
    category: "consumable",
    icon: null,
    iconName: "item_flask",
    quality: "consumable",
    description: "Restores all allied Heroes‘ HP upon pickup.",
    values: [],
  },
  {
    slug: "life-rune",
    gameId: "item_life_rune",
    name: "HP Rune",
    category: "consumable",
    icon: "/items/life-rune.png",
    iconName: "life_rune",
    quality: "consumable",
    cost: 1000,
    stock: 4,
    description: "+1 Life. Revives 10 seconds after death.",
    values: [],
  },
  {
    slug: "joker-coin",
    gameId: "item_joker_coin",
    name: "Jester’s Coin",
    category: "consumable",
    icon: "/items/joker-coin.png",
    iconName: "joker_coin",
    quality: "epic",
    description: "[[head]]Active: Lucky Appraisal[[/]]Flip the coin. [[value]]90%[[/]] chance to gain [[value]]200[[/]] Gold. [[value]]10%[[/]] chance to fail; on failure, Gold gained from this coin becomes debt, and any Gold you earn will first be used to repay the debt.",
    note: "Not affected by Luck.",
    flavor: "Mock not the jester, lest you become the joke.",
    values: [
      {
        key: "current_gold",
        name: "Current Jackpot",
        value: 0.0001,
      },
    ],
  },
  {
    slug: "mushroom-002-d",
    gameId: "item_mushroom_002_d",
    name: "Legendary Agility Shroom",
    category: "consumable",
    icon: "/items/mushroom-002-d.png",
    iconName: "mushroom_002_d",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Agility by [[value]]9[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite. Hang on... what's [Free Ride] supposed to be?",
    values: [],
  },
  {
    slug: "mushroom-005-d",
    gameId: "item_mushroom_005_d",
    name: "Legendary Health Shroom",
    category: "consumable",
    icon: "/items/mushroom-005-d.png",
    iconName: "mushroom_005_d",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max HP by [[value]]230[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite. Hang on... what's [Free Ride] supposed to be?",
    values: [],
  },
  {
    slug: "mushroom-003-d",
    gameId: "item_mushroom_003_d",
    name: "Legendary Intelligence Shroom",
    category: "consumable",
    icon: "/items/mushroom-003-d.png",
    iconName: "mushroom_003_d",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Intelligence by [[value]]9[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite. Hang on... what's [Free Ride] supposed to be?",
    values: [],
  },
  {
    slug: "mushroom-006-d",
    gameId: "item_mushroom_006_d",
    name: "Legendary Mana Shroom",
    category: "consumable",
    icon: "/items/mushroom-006-d.png",
    iconName: "mushroom_006_d",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max MP by [[value]]130[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite. Hang on... what's [Free Ride] supposed to be?",
    values: [],
  },
  {
    slug: "mushroom-001-d",
    gameId: "item_mushroom_001_d",
    name: "Legendary Strength Shroom",
    category: "consumable",
    icon: "/items/mushroom-001-d.png",
    iconName: "mushroom_001_d",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Strength by [[value]]9[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite. Hang on... what's [Free Ride] supposed to be?",
    values: [],
  },
  {
    slug: "mushroom-002-c",
    gameId: "item_mushroom_002_c",
    name: "Major Agility Shroom",
    category: "consumable",
    icon: "/items/mushroom-002-c.png",
    iconName: "mushroom_002_c",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Agility by [[value]]7[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite.",
    values: [],
  },
  {
    slug: "mushroom-005-c",
    gameId: "item_mushroom_005_c",
    name: "Major Health Shroom",
    category: "consumable",
    icon: "/items/mushroom-005-c.png",
    iconName: "mushroom_005_c",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max HP by [[value]]180[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite.",
    values: [],
  },
  {
    slug: "mushroom-003-c",
    gameId: "item_mushroom_003_c",
    name: "Major Intelligence Shroom",
    category: "consumable",
    icon: "/items/mushroom-003-c.png",
    iconName: "mushroom_003_c",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Intelligence by [[value]]7[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite.",
    values: [],
  },
  {
    slug: "mushroom-006-c",
    gameId: "item_mushroom_006_c",
    name: "Major Mana Shroom",
    category: "consumable",
    icon: "/items/mushroom-006-c.png",
    iconName: "mushroom_006_c",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max MP by [[value]]100[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite.",
    values: [],
  },
  {
    slug: "mushroom-001-c",
    gameId: "item_mushroom_001_c",
    name: "Major Strength Shroom",
    category: "consumable",
    icon: "/items/mushroom-001-c.png",
    iconName: "mushroom_001_c",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Strength by [[value]]7[[/]].",
    flavor: "Delicious. Straight delicious. How do you plant this stuff? I need another bite.",
    values: [],
  },
  {
    slug: "mana-potion",
    gameId: "item_mana_potion",
    name: "Mana Potion",
    category: "consumable",
    icon: null,
    iconName: "item_greater_clarity",
    quality: "consumable",
    description: "Restores all allied Heroes' Mana upon pickup.",
    values: [],
  },
  {
    slug: "mushroom-002-a",
    gameId: "item_mushroom_002_a",
    name: "Minor Agility Shroom",
    category: "consumable",
    icon: "/items/mushroom-002-a.png",
    iconName: "mushroom_002_a",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Agility by [[value]]3[[/]].",
    flavor: "Delicious. Straight delicious.",
    values: [],
  },
  {
    slug: "mushroom-005-a",
    gameId: "item_mushroom_005_a",
    name: "Minor Health Shroom",
    category: "consumable",
    icon: "/items/mushroom-005-a.png",
    iconName: "mushroom_005_a",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max HP by [[value]]80[[/]].",
    flavor: "Delicious. Straight delicious.",
    values: [],
  },
  {
    slug: "mushroom-003-a",
    gameId: "item_mushroom_003_a",
    name: "Minor Intelligence Shroom",
    category: "consumable",
    icon: "/items/mushroom-003-a.png",
    iconName: "mushroom_003_a",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Intelligence by [[value]]3[[/]].",
    flavor: "Delicious. Straight up delicious.",
    values: [],
  },
  {
    slug: "mushroom-006-a",
    gameId: "item_mushroom_006_a",
    name: "Minor Mana Shroom",
    category: "consumable",
    icon: "/items/mushroom-006-a.png",
    iconName: "mushroom_006_a",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max MP by [[value]]45[[/]].",
    flavor: "Delicious. Straight delicious.",
    values: [],
  },
  {
    slug: "mushroom-001-a",
    gameId: "item_mushroom_001_a",
    name: "Minor Strength Shroom",
    category: "consumable",
    icon: "/items/mushroom-001-a.png",
    iconName: "mushroom_001_a",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Strength by [[value]]3[[/]].",
    flavor: "Delicious. Straight delicious.",
    values: [],
  },
  {
    slug: "hand-mirror",
    gameId: "item_hand_mirror",
    name: "Mirror of Reversion",
    category: "consumable",
    icon: "/items/hand-mirror.png",
    iconName: "hand_mirror",
    quality: "artifact",
    description: "[[head]]Consume: Temporal Rewind[[/]]Reverts the first [[value]]3[[/]] items in your current inventory to their state at purchase, allowing them to be sold at full original price.",
    flavor: "The Archmage lived his entire life in the shadow of his father, never having met his mother—if he even had one at all. Rumors say this mirror once belonged to her.",
    values: [],
  },
  {
    slug: "mushroom-002-b",
    gameId: "item_mushroom_002_b",
    name: "Moderate Agility Shroom",
    category: "consumable",
    icon: "/items/mushroom-002-b.png",
    iconName: "mushroom_002_b",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Agility by [[value]]5[[/]].",
    flavor: "Delicious. Straight up delicious. What's the farming tech on this?",
    values: [],
  },
  {
    slug: "mushroom-005-b",
    gameId: "item_mushroom_005_b",
    name: "Moderate Health Shroom",
    category: "consumable",
    icon: "/items/mushroom-005-b.png",
    iconName: "mushroom_005_b",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max HP by [[value]]130[[/]].",
    flavor: "Delicious. Straight up delicious. What's the farming tech on this?",
    values: [],
  },
  {
    slug: "mushroom-003-b",
    gameId: "item_mushroom_003_b",
    name: "Moderate Intelligence Shroom",
    category: "consumable",
    icon: "/items/mushroom-003-b.png",
    iconName: "mushroom_003_b",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Intelligence by [[value]]5[[/]].",
    flavor: "Delicious. Straight up delicious. What's the farming tech on this?",
    values: [],
  },
  {
    slug: "mushroom-006-b",
    gameId: "item_mushroom_006_b",
    name: "Moderate Mana Shroom",
    category: "consumable",
    icon: "/items/mushroom-006-b.png",
    iconName: "mushroom_006_b",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases max MP by [[value]]70[[/]].",
    flavor: "Delicious. Straight up delicious. What's the farming tech on this?",
    values: [],
  },
  {
    slug: "mushroom-001-b",
    gameId: "item_mushroom_001_b",
    name: "Moderate Strength Shroom",
    category: "consumable",
    icon: "/items/mushroom-001-b.png",
    iconName: "mushroom_001_b",
    quality: "rare",
    description: "[[head]]Use: Eat.[[/]]Permanently increases base Strength by [[value]]5[[/]].",
    flavor: "Delicious. Straight up delicious. What's the farming tech on this?",
    values: [],
  },
  {
    slug: "treasure-fragment",
    gameId: "item_treasure_fragment",
    name: "Neutral Item Fragment",
    category: "consumable",
    icon: "/items/treasure-fragment.png",
    iconName: "treasure_fragment",
    quality: "artifact",
    description: "[[head]]Consume: Craft[[/]]Increases Neutral Items crafting progress by [[value]]3[[/]].",
    flavor: "Stay one step ahead.",
    values: [],
  },
  {
    slug: "purification-potion",
    gameId: "item_purification_potion",
    name: "Purification Potion",
    category: "consumable",
    icon: "/items/purification-potion.png",
    iconName: "purification_potion",
    quality: "rare",
    stock: 1,
    description: "[[head]]Use: Advanced Purification[[/]]Immediately restores [[value]]35%[[/]] + [[value]]600[[/]] HP to the target and deals the same amount of damage to nearby enemies.",
    values: [
      {
        key: "heal",
        name: "Heal/Damage",
        value: 600,
      },
      {
        key: "pct",
        name: "Bonus Healing/Damage: Target's Max H ×",
        value: 35,
        unit: "%",
      },
      {
        key: "radius",
        name: "Damage Radius",
        value: 260,
        scalesWithAoe: true,
      },
    ],
  },
  {
    slug: "potion-of-forced-growth",
    gameId: "item_potion_of_forced_growth",
    name: "Rapid Growth Tonic",
    category: "consumable",
    icon: "/items/potion-of-forced-growth.png",
    iconName: "potion_of_forced_growth",
    quality: "epic",
    description: "[[head]]Consume: Rapid Growth[[/]]Increases your base all Attributes by an amount equal to the Attributes gained from leveling up [[value]]2[[/]].",
    flavor: "Forcing growth is never a good way.",
    values: [],
  },
  {
    slug: "ravage-potion",
    gameId: "item_ravage_potion",
    name: "Ravage Potion",
    category: "consumable",
    icon: "/items/ravage-potion.png",
    iconName: "ravage_potion",
    quality: "rare",
    stock: 1,
    cooldown: 1,
    description: "[[head]]Use: Advanced Ravage[[/]]Slam the ground, sending out tentacles in all directions that damage and stun all nearby enemy units.",
    values: [
      {
        key: "radius",
        name: "Radius",
        value: 1250,
      },
      {
        key: "duration",
        name: "Duration",
        value: 3.5,
      },
      {
        key: "AbilityDamage",
        name: "Damage",
        value: 200,
      },
      {
        key: "attribute_to_damage",
        name: "Bonus Damage: All Attributes ×",
        value: 200,
        unit: "%",
      },
    ],
  },
  {
    slug: "hyperdimensional-coin",
    gameId: "item_hyperdimensional_coin",
    name: "Realm Shard",
    category: "consumable",
    icon: "/items/hyperdimensional-coin.png",
    iconName: "hyperdimensional_coin",
    quality: "artifact",
    description: "[[head]]Consume: Return[[/]]Used when choosing the next encounter. Adds an extra option: [Return to the Spacetime Relay], allowing you to go back to camp and immediately summon planar travelers/refresh their wares.",
    flavor: "The journey is long—take a moment to rest, resupply, and set out again.",
    values: [],
  },
  {
    slug: "reversal-pocket-watch",
    gameId: "item_reversal_pocket_watch",
    name: "Reversal Watch",
    category: "consumable",
    icon: "/items/reversal-pocket-watch.png",
    iconName: "reversal_pocket_watch",
    quality: "epic",
    description: "[[head]]Consume: Time Reversal[[/]]Inverts the current day–night cycle and grants you both daytime and nighttime bonuses for the duration of the current encounter.",
    flavor: "Most artifacts used by Aghanim possess powers tied to time; this pocket watch can turn it upside down.",
    values: [],
  },
  {
    slug: "scroll-of-the-painter-master",
    gameId: "item_scroll_of_the_painter_master",
    name: "Scroll of the Master Painter",
    category: "consumable",
    icon: "/items/scroll-of-the-painter-master.png",
    iconName: "scroll_of_the_painter_master",
    quality: "consumable",
    description: "[[head]]Consume: Reveal[[/]]Reveals vision of the current Stage for [[value]]150[[/]] seconds.",
    flavor: "Always see more. Always see farther.",
    values: [],
  },
  {
    slug: "substitute-doll",
    gameId: "item_substitute_doll",
    name: "Substitute Doll",
    category: "consumable",
    icon: "/items/substitute-doll.png",
    iconName: "substitute_doll",
    quality: "artifact",
    description: "[[head]]Consume: Substitute[[/]]Grants [[value]]2[[/]] stack(s) of [Substitute]. When taking lethal damage, negates that damage and becomes invulnerable for [[value]]2[[/]] seconds.",
    flavor: "Dirty witchcraft, so shady and outrageous... wait, I'm the one using it? Then never mind.",
    values: [],
  },
  {
    slug: "new-bottle",
    gameId: "item_new_bottle",
    name: "Bottle",
    category: "encounter",
    icon: null,
    iconName: "item_bottle4",
    quality: "consumable",
    description: "[[head]]Use: Restoration[[/]]Restores HP and Mana over [[value]]5[[/]] seconds.",
    note: "[[color:#606060]]Considered a Health Regeneration effect.[[/]]",
    flavor: "An old bottle that survived the ages, the contents placed inside become enchanted.",
    values: [
      {
        key: "base_hp_regen",
        name: "Health Regeneration Per Second",
        value: 40,
      },
      {
        key: "hp_restore_pct",
        name: "Max HP Restored Per Second",
        value: 3,
        unit: "%",
      },
      {
        key: "base_mp_regen",
        name: "Mana Regeneration Per Second",
        value: 20,
      },
      {
        key: "mana_restore_pct",
        name: "Max Mana Restored Per Second",
        value: 2,
        unit: "%",
      },
      {
        key: "duration",
        name: "Duration",
        value: 5,
      },
      {
        key: "max_charge",
        name: "Max Charges",
        value: 3,
      },
    ],
  },
  {
    slug: "hd-encounter-meteor-hammer",
    gameId: "item_hd_encounter_meteor_hammer",
    name: "Nether Meteor Hammer",
    category: "encounter",
    icon: null,
    iconName: "item_meteor_hammer",
    quality: "epic",
    cost: 2350,
    description: "[[head]]Active: Meteor Hammer[[/]] Channeling - After a successful channel, summons a meteor that strikes enemies within [[value]]400[[/]] range, causing [[value]]1.5[[/]] seconds of stun and impact damage. Deals continuous damage to enemy units and buildings for [[value]]6[[/]] seconds.",
    values: [],
  },
  {
    slug: "aghsfort-drow-ranger-invis-sword",
    gameId: "item_aghsfort_drow_ranger_invis_sword",
    name: "Silent Killer",
    category: "encounter",
    icon: null,
    iconName: "item_invis_sword",
    cooldown: 2,
    description: "[[head]]Active: Shadow Walk[[/]]Makes you invisible for [[value]]14[[/]] seconds, or until you attack or cast. While Shadow Walk is active, you move [[value]]20%[[/]] faster and can move through units. Breaking invisibility with an attack deals [[value]]100[[/]] bonus Physical Damage.",
    note: "Has a [[value]]0.5[[/]] second fade time.",
    flavor: "The sword of a fallen king, it allows you to move unseen and strike from the shadows.",
    values: [
      {
        key: "bonus_damage",
        name: "Attack Damage",
        value: 0,
      },
      {
        key: "bonus_attack_speed",
        name: "Attack Damage",
        value: 30,
      },
    ],
  },
]
